config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :taggings
  resources :tags
  resources :likes
  resources :permissions
  resources :roles
  resources :posts
  resources :threads
  resources :categories
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/permission.rb
class Permission < ApplicationRecord
  belongs_to :role
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :thread
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :thread
end

app/models/thread.rb
class Thread < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/taggings_controller.rb
class TaggingsController < ApplicationController
  before_action :set_tagging, only: %i[ show edit update destroy ]

  # GET /taggings or /taggings.json
  def index
    @taggings = Tagging.all
  end

  # GET /taggings/1 or /taggings/1.json
  def show
  end

  # GET /taggings/new
  def new
    @tagging = Tagging.new
  end

  # GET /taggings/1/edit
  def edit
  end

  # POST /taggings or /taggings.json
  def create
    @tagging = Tagging.new(tagging_params)

    respond_to do |format|
      if @tagging.save
        format.html { redirect_to tagging_url(@tagging), notice: "Tagging was successfully created." }
        format.json { render :show, status: :created, location: @tagging }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tagging.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /taggings/1 or /taggings/1.json
  def update
    respond_to do |format|
      if @tagging.update(tagging_params)
        format.html { redirect_to tagging_url(@tagging), notice: "Tagging was successfully updated." }
        format.json { render :show, status: :ok, location: @tagging }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tagging.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /taggings/1 or /taggings/1.json
  def destroy
    @tagging.destroy!

    respond_to do |format|
      format.html { redirect_to taggings_url, notice: "Tagging was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tagging
      @tagging = Tagging.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tagging_params
      params.require(:tagging).permit(:tag_id, :thread_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/taggings_helper.rb
module TaggingsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/threads_helper.rb
module ThreadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/taggings/_form.html.erb
<%= form_with(model: tagging) do |form| %>
  <% if tagging.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tagging.errors.count, "error") %> prohibited this tagging from being saved:</h2>

      <ul>
        <% tagging.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :tag_id, style: "display: block" %>
    <%= form.text_field :tag_id %>
  </div>

  <div>
    <%= form.label :thread_id, style: "display: block" %>
    <%= form.text_field :thread_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/taggings/_tagging.html.erb
<div id="<%= dom_id tagging %>">
  <p>
    <strong>Tag:</strong>
    <%= tagging.tag_id %>
  </p>

  <p>
    <strong>Thread:</strong>
    <%= tagging.thread_id %>
  </p>

</div>

app/views/taggings/edit.html.erb
<h1>Editing tagging</h1>

<%= render "form", tagging: @tagging %>

<br>

<div>
  <%= link_to "Show this tagging", @tagging %> |
  <%= link_to "Back to taggings", taggings_path %>
</div>

app/views/taggings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Taggings</h1>

<div id="taggings">
  <% @taggings.each do |tagging| %>
    <%= render tagging %>
    <p>
      <%= link_to "Show this tagging", tagging %>
    </p>
  <% end %>
</div>

<%= link_to "New tagging", new_tagging_path %>

app/views/taggings/new.html.erb
<h1>New tagging</h1>

<%= render "form", tagging: @tagging %>

<br>

<div>
  <%= link_to "Back to taggings", taggings_path %>
</div>

app/views/taggings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tagging %>

<div>
  <%= link_to "Edit this tagging", edit_tagging_path(@tagging) %> |
  <%= link_to "Back to taggings", taggings_path %>

  <%= button_to "Destroy this tagging", @tagging, method: :delete %>
</div>