config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :taggings
  resources :tags
  resources :likes
  resources :permissions
  resources :roles
  resources :posts
  resources :threads
  resources :categories
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/permission.rb
class Permission < ApplicationRecord
  belongs_to :role
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :thread
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :thread
end

app/models/thread.rb
class Thread < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: %i[ show edit update destroy ]

  # GET /reports or /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1 or /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports or /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to report_url(@report), notice: "Report was successfully created." }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1 or /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to report_url(@report), notice: "Report was successfully updated." }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1 or /reports/1.json
  def destroy
    @report.destroy!

    respond_to do |format|
      format.html { redirect_to reports_url, notice: "Report was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def report_params
      params.require(:report).permit(:reason, :user_id, :post_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/taggings_helper.rb
module TaggingsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/threads_helper.rb
module ThreadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/reports/_form.html.erb
<%= form_with(model: report) do |form| %>
  <% if report.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
        <% report.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :reason, style: "display: block" %>
    <%= form.text_area :reason %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :post_id, style: "display: block" %>
    <%= form.text_field :post_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/reports/_report.html.erb
<div id="<%= dom_id report %>">
  <p>
    <strong>Reason:</strong>
    <%= report.reason %>
  </p>

  <p>
    <strong>User:</strong>
    <%= report.user_id %>
  </p>

  <p>
    <strong>Post:</strong>
    <%= report.post_id %>
  </p>

</div>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render "form", report: @report %>

<br>

<div>
  <%= link_to "Show this report", @report %> |
  <%= link_to "Back to reports", reports_path %>
</div>

app/views/reports/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Reports</h1>

<div id="reports">
  <% @reports.each do |report| %>
    <%= render report %>
    <p>
      <%= link_to "Show this report", report %>
    </p>
  <% end %>
</div>

<%= link_to "New report", new_report_path %>

app/views/reports/new.html.erb
<h1>New report</h1>

<%= render "form", report: @report %>

<br>

<div>
  <%= link_to "Back to reports", reports_path %>
</div>

app/views/reports/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @report %>

<div>
  <%= link_to "Edit this report", edit_report_path(@report) %> |
  <%= link_to "Back to reports", reports_path %>

  <%= button_to "Destroy this report", @report, method: :delete %>
</div>